lib/cli.js
lib/lesshint.js
lib/linter.js
lib/linters/duplicate_property.js
lib/linters/import_path.js
lib/linters/property_units.js
lib/linters/qualifying_element.js
lib/linters/single_line_per_property.js
lib/linters/single_line_per_selector.js
lib/linters/space_after_comma.js
lib/linters/space_after_property_value.js
lib/linters/space_before_comma.js
lib/linters/space_between_parens.js
lib/linters/string_quotes.js
lib/linters/trailing_whitespace.js
lib/reporters/stylish.js

This is in preparation for the separation of warnings from errors, and the addition of errors as a separate result type. Passes `npm test`

changing the vernacular of 'errors' to 'results'

---

lib/config/defaults.json
lib/lesshint.js
lib/linter.js
test/specs/lesshint.js
test/specs/linter.js

In reference to: https://github.com/lesshint/lesshint/issues/44
This is dependant upon https://github.com/lesshint/lesshint/pull/46
Defines warnings vs errors. Since linters aren't inheriting anything from a parent object and are duplicating a lot of code, the code to allow overriding of their result type will have to be pasted manually in each linter. This PR accounts for missing `type` property on each result and adds the default of `linter.resultType.warning` if it's not found.
This can be considered a minor semver change for the fact that it significantly adds to functionality, or a patch change since it contains no breaking changes.

Errors vs warnings

---

lib/linters/attribute_quotes.js
test/specs/linters/attribute_quotes.js

Support value-less attributes (a.k.a. boolean attributes)

fix(attributeQuotes): skip validation for value-less selector

---

lib/cli.js
lib/lesshint.js
test/data/config/bad.json
test/specs/cli.js
test/specs/lesshint.js

As discussed in #62. Lets make sure we don't try to parse all kinds of exception messages, just the ones thrown by `gonzales-pe`. All other messages should just be rethrown and handled further up, for example in the `CLI` or by `gulp-lesshint`.

Better handling and catching of errors.

---

lib/linters/property_units.js
test/specs/linters/property_units.js

This MR skips variable declarations inside of classes similar to the example below.
```less
ul {
@var-name: 25px;
}
```

Skip variable declarations in propertyUnits linter

---

lib/linters/single_line_per_property.js
test/specs/linters/single_line_per_property.js

I extended the singleLinePerProperty linter to also include the 'include' and 'extend' types of gonzales-pe as those seem to be matched by ```.mixin();```. If you would like to include more or less types, please let me know.

Ensure that mixins are on seperate lines

---

lib/config/defaults.json
lib/linter.js
lib/linters/README.md
lib/linters/selector_naming.js
test/specs/linters/selector_naming.js

Allows to check for case, dashes and underscores.
Can be combined to approximate camelcase, train, snake case.
One can also add a white list with the excludes option.
Actual naming conventions like camel case or bem notation might be
a second step.
Issue  #105

feat(linter): selector naming convention #105

---

lib/linters/duplicate_property.js
test/specs/linters/duplicate_property.js

Otherwise crashes on:
```less
.myblock {
@a: red;
@b: 3px;
}
```

Fix duplicateProperty crashing on local variables

---

lib/cli.js
test/data/config/config.json
test/data/config/exclude-only-one.json
test/data/excluded-files/exclude-me-too.less
test/specs/cli.js
test/specs/config-loader.js
test/specs/lesshint.js

The current code tramples the excludedFiles setting in the config file
with either the value supplied on the command line or an empty array.
This fixes that; additionally, if excludedFiles is specified in both
the config file and on the command line, the union of both is used.
Tests have been updated/added to cover the different scenarios.

Honor excludedFiles in the config file

---

gulpfile.js
test/specs/linter.js
test/specs/linters/import_path.js
test/specs/linters/single_line_per_property.js
test/specs/linters/space_after_property_value.js
test/specs/linters/space_around_comma.js
test/specs/linters/space_between_parens.js

the linter was pitching a fit about array definition indentation when the array def contained multiple objects.
also separated the lint and config task deps for the test task, enforcing a linear and synchronous execution. was having an issue of the coverage task failing because of a syntax error before the lint task could tell me where it was.

synchronous gulp task execution, linter indentation fixes

---

lib/linters/space_after_property_colon.js
test/specs/linters/space_after_property_colon.js

Adds "at_least_one_space" option to "spaceAfterPropertyColon" linter. Thats allows to align equal values  of related properties. Like so:
```
.foo {
width:  20px;
height: 20px;
}
```
Resolves #154

New option for "spaceAfterPropertyColon" linter

---

lib/linters/README.md

The fragment identifier for the **depthLevel** section should be `#depthlevel` (lowercase).

Fix fragment identifier (#depthlevel)

---

lib/linters/decimal_zero.js
test/specs/linters/decimal_zero.js

I think I found a minor regression in the recent patch for `decimalZero`. 
The issues I found:
* Earlier `1.25` wouldn't be reported when `style` was `trailing` but now it was. 
* Earlier `1.250` wouldn't be reported when `style` was `both` but now it was. 
@CITguy Could you just take a look at this fix and see if it does what you expect?

Fix possible decimalZero regression with floats greater than 1

---

package.json

- Provides a workaround within enterprises where the default git protocol port is blocked.
- Use github URL format in package.json instead of a git only URL. This prevents npm from failing when and rather use https ports instead of git protocol port (9418) id git global config are set via: `git config --global url."https://".insteadOf git://`

Fix gonazel-pe not being fetched when git protocol port is blocked

---

lib/lesshint.js
test/specs/lesshint.js

-Fix case where report fullPath field would have multiple slashes
separating directories
ex. `lesshint src/` would produce reports with fullPaths like `src//foo/bar/baz.less`

Strip trailing slashes from directory argument

---

lib/linters/property_ordering.js
test/specs/linters/property_ordering.js

This fixes two issues:
* It treated all the declarations in nested rules as one and thus complained about them. See #177.
* It would complain on variables that weren't alphabetically ordered.

2.0 propertyOrdering bugs

---

lib/linters/README.md
lib/linters/decimal_zero.js
test/specs/linters/decimal_zero.js

As per #165.
TLDR, `decimalZero` will now only check if there's always/never a leading/trailing decimal number, not that it's always a zero there (even if there were other numbers too).

Behavior change in decimalZero 

---

lib/linters/space_between_parens.js
test/specs/linters/space_between_parens.js

just stripping the newline characters from raws for now. we can get fancier if we decide to implement something more intelligent. this should cover most cases in the meantime.

fixes #130: spaceBetweenParens fails with mulitiline definitions

---

lib/config/defaults.json
lib/linter.js
lib/linters/README.md
lib/linters/important_rule.js
lib/linters/qualifying_element.js
lib/linters/space_around_comma.js
test/specs/linter.js
test/specs/linters/attribute_quotes.js
test/specs/linters/qualifying_element.js
test/specs/linters/space_around_comma.js
test/specs/linters/url_quotes.js
test/specs/util.js

This is my proposal for the spaceAroundComma fix when newlines are used to separate comma-delimited lists. `allowNewline` set to `true` will skip any verification of space around a comma if a newline is detected, based on the `style` option chosen.

fixes #119: adds allowNewline option to spaceAroundComma

---

README.md

It's a little confusing that the first example of a `.lesshintrc` file is not actually valid.

Added brackets around .lesshintrc sample in README

---

test/specs/linters/decimal_zero.js
test/specs/linters/hex_notation.js

Found these two tests in decimalZero and hexNotation that didn't actually do anything. Increases our coverage a little bit too 😉

Fixes for some broken tests 

---

lib/linters/import_path.js
test/specs/linters/import_path.js

This is just a simple regex replace on the `params` node property. It should hold us over until https://github.com/webschik/postcss-less/issues/57 is fixed. Not an ideal fix by any means, but the likelihood of the import options list growing faster than we can update this regex is slim to none.
Added a few dupe tests with an import option just to make sure it doesn't break moving forward.

fixes #236: import options breaking importPath linter

---

test/data/config/failingLinter.json
test/plugins/failingLinter.js
test/specs/cli.js

Tests that a CLI fail and a config fail both cause the appropriate errors.
Fixes #205.

Failing linter tests

---

lib/linters/space_before_brace.js
test/specs/linters/space_before_brace.js

This fixes #244 where setting "space before brace" to "new_line" did not allow you to indent the code.
It also fixes another issue in the "one_space" reg ex which used \s instead of space literal. \s does not mean space it means all whitespace characters so it would also pick up new lines (providing you use Unix style of just LF and not windows which uses two characters) and tabs.
Test have been provided and all pass.

Space before brace new line and whitespace

---

lib/linters/duplicate_property.js
test/specs/linters/duplicate_property.js

DuplicateProperty config should ingnore duplicate property ending with a "+" or "+_". This is a LESS merge feature. See: http://lesscss.org/features/#merge-feature

Add support for LESS merge feature

---

lib/linter.js
test/data/inline-options/options-invalid.less
test/specs/linter.js

As of 2.1.1 an invalid inline option, (say, `// lesshint fnord`) will be reported unhelpfully by lesshint as `TypeError: Cannot read property 'line' of undefined`. This fixes the Error construction in parseRules to report the problem more clearly.
Incidentally, it seems to my amateur eye that it wouldn't be terribly difficult to report this inline with other errors, the same way CSS parse errors are handled. I could take a crack at that too, if it seems like a useful feature.

Report invalid inline options

---

lib/linters/newline_after_block.js
test/specs/linters/newline_after_block.js

Allow trailing whitespace to be present on the empty line. This will hopefully fix #245.

Account for trailing whitespace in newlineAfterBlock

---

lib/linter.js
test/specs/linter.js

Fixes #272.
Rules can just say they're `true` rather than the full `{ enabled: true
}`.

Added a shorthand `true` for `{ enabled: true }`

---

bin/lesshint
lib/cli.js
test/data/config/three-warns.json
test/data/config/two-warns.json
test/specs/cli.js

Where number below `max-warnings` result in a zero exit code. This is
desirable for projects that allow a certain amount of warnings to pass
the build system, and the build system that relies on a zero exit code
for the build to pass.
We default to 0, for backwards compatibility. A max warning of -1 will
allow any number of warnings to pass.

Add a max-warnings cli flag

---

lib/lesshint.js
test/specs/cli.js
test/specs/lesshint.js

Fixes #282.
I held off from documenting in this PR since until #283 is resolved I don't believe it would be easy for users to use this.

Allow reporters to be objects, not just file paths

---

lib/config/defaults.json
lib/linters/README.md
lib/linters/single_line_per_property.js
test/specs/linters/single_line_per_property.js

I'm not really satisfied with the `allowSingleLineRules` option name. Suggestions welcome!
Closes #269.

Add allowSingleLineRules option to singleLinePerProperty

---

lib/lesshint.js
test/specs/lesshint.js

As discussed in #251.
Can anyone see any BC breaks with this approach? I'm keeping the old `excludedFiles` check since we want people to exclude a single file.

excludedFiles should check paths before reading them

---

bin/lesshint
lib/cli.js
package.json
test/specs/cli.js

This allows consumers of the CLI function to not randomly close when the exit package is called.
Fixes #281.

Moved require('exit') to bin\lesshint

---

lib/linter.js

Fixes #327.
You can't just politely ask `require` if something exists; you can only attempt to load it and try/catch the logic.

Added a process.cwd check for requiring linters

---

lib/errors/runner-error.js
lib/runner.js

* Reject `Runner` with real `Error`s.
* Fix handling of `--max-warnings=-1`. Closes #321.
* Fix a minor refactor typo with custom linters.
#321 among others.
@kokarn Is this what you had in mind? Hope I didn't step on any toes 😬

Final 3.0 CLI touches

---

lib/linters/README.md

The Twitter link for mdo was relative instead of absolute.

Fixed @mdo URL typo in linters/README.md

---

.gitignore
gulpfile.js
package.json

Since `gulp-mocha 4.0` spawns a child process we need a coverage tool that handles that.
To get it working on older npm versions which doesn't dedupe by default, we need to explicitly include mocha as a dependency as well.
Thanks to @kokarn for the rubber ducking session!
N/A
Nope, it should be self-explanatory.

Replace istanbul with nyc

---

lib/linters/space_around_operator.js
test/specs/linters/space_around_operator.js

Solve #349 
```css
h {
margin-left: -(1px); // fails
}
```
Nope. A lot of copy/paste code in the test section.
I am not sure about my changes. Any help is welcome!

Allow negative values before a (. Close #349

---

lib/errors/lesshint-error.js
lib/errors/runner-error.js
test/specs/errors/lesshint-error.js
test/specs/errors/runner-error.js

Point 3 of #357, kinda. Since we broke that functionality in `3.0` with our custom errors which this commit fixes.
Not really.

Handle both strings and error objects in custom errors

---

lib/config-loader.js
lib/linter.js
test/specs/config-loader.js
test/specs/linter.js

#372 
Basic gist is that I am adding _path to the config data that contains the path to the .lesshintrc file. This allows me to find custom linters relative to .lesshintrc.

If custom linter is not found by absolute url or relative to cwd, check relative to .lesshintrc

---

lib/config/defaults.json
lib/linter.js
lib/linters/README.md
lib/linters/color_variables.js
test/specs/linters/color_variables.js

More related to #372 
This is adding a linter that prohibits hex colors unless used for variable assignment.

Add color variables linter

---

README.md
bin/lesshint
lib/runner.js
test/specs/bin/lesshint.js
test/specs/cli.js

**Changes proposed in this PR:** 
Changed the approach of exit codes to:
- Linting errors with a severity of `warning` gives exit code `0`
- Unless `--max-warnings` flag is set and the number of linting errors with a severity of `warning` is greater than the given value. Then it gives exit code `1`
- Linting errors with a severity of `error` gives exit code `1`
**Which issue, if any, does this resolve?** 
Will close #394. 
**Is there anything in this PR that needs extra explaining or should something specific be focused on?** 
The whole logic was already discussed in corresponding GitHub issue (#394).
@jwilsson please take a look.

Warnings gives exit code 0

---

docs/developer-guide/api/lesshint.md
lib/lesshint.js
lib/runner.js
package.json
test/specs/lesshint.js

This is a more general method which works on globs and handles everything instead of having separate methods. It'll check `fileExtensions` and `excludedFiles` options for backwards compatibility but that can just be specified in the glob pattern.
With `globby@7` this should work exactly like `Lesshint.checkPath()` does today with regards to walking directories (that's the point of this new method at least).
Point 4 of #357.
I'm thinking we deprecate these methods in favor of `Lesshint.checkFiles()`:
* `Lesshint.checkDirectory()`
* `Lesshint.checkFile()`
* `Lesshint.checkPath()`
They're only marked as deprecated in the docs and I say we remove …

Add a Lesshint.checkFiles() method

---

lib/linters/single_line_per_selector.js
test/specs/linters/single_line_per_selector.js

This comes with a slight behaviour change. It'll no longer report the first selector on a line, only the following ones.
#346
No, I think it should be pretty straight forward.
I don't think this should be merged until we're ready for a new major version, though.

Rewrite singleLinePerSelector

---

docs/developer-guide/api/runner.md

``` args``` is the right parameter to set less files to runner

fix(doc): change paths to args

---

lib/linters/zero_unit.js

these rules deal in unitless numbers; to suggest they require units is an error.
see: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
would ignore `flex` too, but it has `flex-basis` as its third input, which may need a unit.
none

zeroUnit: exclude flex-grow/-shrink

---

lib/linters/property_ordering.js
test/specs/linter.js
test/specs/linters/property_ordering.js

Following  #496 
Sorry I did not see it before but it's now really boring to only have a "not concentric" error. 
Here I show a "move it before" message, it's not perfect as you got it for every line, but it's a start. 
I will look later if we can find the correct position on first time.
(It may be better to merge this in a 5.2.1 and create a feature request for later)

Better report on ordering errors
