lesshint/lesshint

lib/config/defaults.json, lib/linter.js, lib/linters/README.md, lib/linters/property_ordering.js, test/specs/linters/property_ordering.js
Thanks for all the hard work guys!
I just ran into the question of ordering properties alphabetically. I noticed that the issue was brought up, so I put something together really quick. Let me know how it looks.
@jsdevel
=> Property Ordering by Alpha

lib/linters/single_line_per_property.js, test/specs/linters/single_line_per_property.js
=> feat(singleLinePerProperty): allow inline comments

lib/linters/url_quotes.js, test/specs/linters/url_quotes.js
=> fix verbiage in url_quotes linter

lib/config/defaults.json, lib/linters/README.md, lib/linters/property_units.js, test/specs/linters/property_units.js
propertyUnits: valid, invalid specification. addresses #36
=> propertyUnits: valid, invalid specification. addresses #36

lib/linters/attribute_quotes.js, lib/linters/id_selector.js, lib/linters/import_path.js, lib/linters/qualifying_element.js, lib/linters/single_line_per_selector.js, lib/linters/space_before_brace.js, package.json, test/specs/linters/attribute_quotes.js, test/specs/linters/qualifying_element.js, test/specs/linters/single_line_per_selector.js, test/specs/linters/space_around_comma.js, test/specs/linters/space_before_brace.js, test/specs/linters/space_between_parens.js
Still work in progress.
Everything but `qualifyingElement` and `spaceBeforeBrace` is fixed and works.
=> Update gonzales-pe to 3.0.0-beta

lib/linters/import_path.js, test/specs/linters/import_path.js
This MR skips all @import statements with url()s. Should fix #80.
=> Skip url @import statements

lib/linters/single_line_per_property.js, package.json
I'm a bit unsure whether we should pull it straight from Git or include the whole library in our source.
Pros:
- Bug fixes can be published straight away.
- Including the whole lib in our source will probably be quite large.
- ???
Cons:
- We might accidentally break things with a bad push.
- ???
=> Replace gonzales-pe with updated fork

lib/linters/space_around_operator.js, test/specs/linters/space_around_operator.js
@jwilsson - some basic condition to prevent crashing.
=> Fixes #120 bug

lib/linters/space_around_operator.js, test/specs/linters/space_around_operator.js
@jwilsson - I had finally time to fix recent issues with negative numbers. Please take a look,
=> Fixes upstream #124 bug with negative numbers

lib/reporters/teamcity.js, test/specs/reporters/teamcity.js
sorry... my bad :D square brackets are not allowed :)
=> teamcity fix

lib/cli.js
TeamCity needs to know that test passed.
https://github.com/lesshint/lesshint/blob/master/lib/reporters/teamcity.js#L37
=> call reporter even if no errors found

lib/config/defaults.json, lib/linter.js, lib/linters/README.md, lib/linters/depth_level.js, test/specs/linters/depth_level.js
New Rule - Depth Level. Sets the depth of nested styles in every parent
style.
=> New Rule - Depth Level.

lib/linters/decimal_zero.js, test/specs/linters/decimal_zero.js
* check all "number" values in declaration
* more robust regexes
* refactored tests
closes #137
=> fix(decimalZero): correct false positive

README.md, lib/cli.js, lib/lesshint.js, lib/reporters/default.js, package.json, test/specs/lesshint.js, test/specs/reporters/default.js
Closes #147.
The `stylish` reporter now lives in https://github.com/lesshint/reporter-stylish and there's a simple, no colors reporter included here which is used when no reporter is passed.
=> Reporter changes

lib/linters/space_around_operator.js, test/specs/linters/space_around_operator.js
=> spaceAroundOperator shouldn't report negative variables

lib/linters/attribute_quotes.js, lib/linters/decimal_zero.js, lib/linters/hex_length.js, lib/linters/hex_notation.js, lib/linters/hex_validation.js, lib/linters/id_selector.js, lib/linters/important_rule.js, lib/linters/property_units.js, lib/linters/qualifying_element.js, lib/linters/selector_naming.js, lib/linters/single_line_per_selector.js, lib/linters/space_after_property_colon.js, lib/linters/space_after_property_value.js, lib/linters/string_quotes.js, lib/linters/trailing_semicolon.js, lib/linters/zero_unit.js, test/specs/linters/hex_length.js, test/specs/linters/hex_notation.js, test/specs/linters/hex_validation.js, test/specs/linters/important_rule.js, test/specs/linters/qualifying_element.js, test/specs/linters/space_after_property_colon.js, test/specs/linters/trailing_semicolon.js
Fixed a bunch of issues where the column reporting was a bit off or wrong.
I also found a false positive in `spaceAfterPropertyColon` where it would report errors if there were spaces before the colon.
=> Fixes to column reporting

test/specs/lesshint.js
=> Make proper use of path.join() in tests

lib/linters/url_quotes.js
=> Add an extra safety check to urlQuotes

lib/linters/zero_unit.js, test/specs/linters/zero_unit.js
=> Don't check function arguments in zeroUnit

lib/linters/single_line_per_property.js, test/specs/linters/single_line_per_property.js
Props @wareczek (idea taken from an old comment that was deleted for some reason).
Ref #177.
=> Ensure singleLinePerProperty checks each rule on its own

lib/linters/empty_rule.js, package.json, test/specs/linters/empty_rule.js, test/specs/linters/space_before_brace.js
Also updated our postcss-less dep version to the latest.
=> fixes #200. emptyRule false positive on mixin func defs

lib/linters/empty_rule.js, lib/linters/space_before_brace.js, test/specs/linters/empty_rule.js, test/specs/linters/space_before_brace.js
@wareczek this should take care of it
=> more fixes for #200, emptyRule and spaceBeforeBrace

lib/linters/decimal_zero.js
Not much to say, simple little fix.
=> Fix line reporting in decimalZero

package.json
The title says it all. Nothing more, nothing less.
=> Update gulp-mocha to 3.x

lib/linters/space_between_parens.js
=> Fixed line reporting in spaceBetweenParens

lib/linters/string_quotes.js, test/specs/linters/string_quotes.js
=> Ensure that stringQuotes checks at-rules

lib/linters/newline_after_block.js, test/specs/linters/newline_after_block.js
=> Fixed false positive in newlineAfterBlock with nested blocks

lib/linters/single_line_per_selector.js, test/specs/linters/single_line_per_selector.js
=> Ensure that singleLinePerSelector only reports each selector once

lib/cli.js, lib/linter.js
To make make debugging easier in large projects.
=> Include the currently checked file in exceptions

lib/linters/string_quotes.js, test/specs/linters/string_quotes.js
=> stringQuotes shouldn't check string-less at-rules

lib/reporters/json.js, test/specs/reporters/json.js
Logs stringified results as JSON.
Fixes #280.
=> Added a JSON reporter

test/specs/cli.js
=> Restore console spies before assertions

lib/linter.js, test/specs/linter.js
Fixes #287.
It's computed by keeping the "raw" (trailing endlines included) lines from inputs.
Note that these are 0-based indices instead of 1-based like columns and lines.
=> Absolute positions

lib/lesshint.js
=> Explicit default reporter

lib/config-loader.js, lib/lesshint.js, test/specs/config-loader.js, test/specs/lesshint.js
#290 
I diverted a bit from the original issue, a file or directory can be passed and the method will figure out what needs to be done.
=> Add a Lesshint.getConfig() method

bin/lesshint, lib/cli.js, lib/lesshint.js, package.json, test/specs/cli.js
N/A
I'd appreciate an extra set of eyes on `lib/lesshint.js` since that's where the biggest changes are.
=> Replace Vow with native Promises

lib/linter.js, test/specs/linter.js
This is technically backwards incompatible since some tests are modified.
Some incorrect tests were fixed too.
N/A
Nothing in particular.
=> Make sure fullPath is a full path

lib/index.js, package.json, test/specs/index.js
=> Expose Lesshint and Runner classes in the public API

lib/linters/attribute_quotes.js, lib/linters/id_selector.js, lib/linters/property_units.js, lib/linters/selector_naming.js, test/specs/linters/attribute_quotes.js, test/specs/linters/id_selector.js, test/specs/linters/selector_naming.js
#308 (and other bugs without issues) 
Nothing in particular.
=> Fix a bunch of line reporting bugs

lib/linters/space_around_comma.js, test/specs/linters/space_around_comma.js
It is a fix for the issue #318
=> Issue #318 - handle unexpected comma in space_around_comma linter

lib/linter.js, test/data/inline-options/endlines.less, test/specs/linter.js
Regular expressions are hard!
Fixes #310.
=> Fixed linesRaw regexp to allow for duplicate `\n`s

lib/linters/url_quotes.js, test/specs/linters/url_quotes.js
#364 
Seems pretty straightforward.
=> Add check for variable in url quotes linter.

lib/lesshint.js, lib/linter.js, test/plugins/noArrayLinter.js, test/specs/linter.js, test/specs/util.js
The `linter.js` file has grown out of hand so I decided to refactor it into a proper class, renamed some methods, merged others, but mostly laid the ground work for a better structure for inline configuration comments.
N/A
The test changes could use an extra pair of eyes, but I think they're alright since this isn't a public API. The rest of the changes are basically copy/paste and some renaming.
~~Still a WIP so don't merge it, but feedback is appreciated!~~
Edit: No longer a WIP, ready for review!
=> Linter refactor

lib/linters/space_after_property_value.js, test/specs/linters/space_after_property_value.js
=> #368 spaceAfterPropertyValue bug with !important

docs/developer-guide/API.md, docs/developer-guide/api/utils.md, lib/index.js, lib/linters/attribute_quotes.js, lib/linters/decimal_zero.js, lib/linters/hex_length.js, lib/linters/hex_notation.js, lib/linters/hex_validation.js, lib/linters/id_selector.js, lib/linters/import_path.js, lib/linters/property_ordering.js, lib/linters/property_units.js, lib/linters/qualifying_element.js, lib/linters/selector_naming.js, lib/linters/single_line_per_selector.js, lib/linters/space_around_comma.js, lib/linters/space_around_operator.js, lib/linters/space_between_parens.js, lib/linters/string_quotes.js, lib/linters/universal_selector.js, lib/linters/url_format.js, lib/linters/url_quotes.js, lib/linters/variable_value.js, lib/linters/zero_unit.js, lib/utils/index.js, lib/utils/is-absolute-url.js, lib/utils/is-variable.js, lib/utils/parse-selector.js, lib/utils/parse-value.js, test/specs/index.js
N/A
Not really, it should be pretty self-explanatory.
=> Refactor some common operations into utils

lib/linter.js
#388
Not really, it should be straightforward.
=> Don't modify the passed config object in Linter class

.travis.yml, appveyor.yml, package.json
* Update `chai` to `^4.0.0`
* Update `nyc` to `^11.0.0`
* Run CI tests on Node 8
N/A
Nope, just wanna see that everything passes.
=> Bump dependencies

lib/linters/hex_notation.js, lib/linters/hex_validation.js
=> Use postcss-values-parser isColor where applicable

lib/linters/space_around_operator.js, test/specs/linters/space_around_operator.js
#343
No, should be pretty straightforward.
=> Fix column reporting in spaceAroundOperator

docs/developer-guide/api/lesshint.md, lib/lesshint.js, test/specs/lesshint.js
No issue, just a quick enhancement.
Nope.
=> Return the complete config object from Lesshint.configure()

lib/linters/url_format.js, lib/linters/url_quotes.js, test/specs/linters/url_quotes.js
No issue.
No, it should be straight forward.
=> Refactor url* rules position reporting

lib/linters/space_before_brace.js, test/specs/linters/space_before_brace.js
#231
This fixed a lot of other column/line position issues too. Found some invalid tests that I removed too. I also removed exceptions for `@import` nodes since they're no longer passed to this rule.
=> Fix spaceBeforeBrace reporting on multi-line selectors

lib/linters/space_after_property_value.js, test/specs/linters/space_after_property_value.js
#344
No, it should be pretty self explanatory.
=> Fix column reporting in spaceAfterPropertyValue

lib/linters/hex_length.js, lib/linters/hex_notation.js, lib/linters/hex_validation.js, test/specs/linters/hex_length.js, test/specs/linters/hex_notation.js, test/specs/linters/hex_validation.js
=> Refactor hex* rules position reporting

lib/linters/universal_selector.js
=> Refactor universalSelector position reporting

lib/linters/border_zero.js
=> Refactor borderZero position reporting

lib/linters/variable_value.js
=> Refactor variableValue position reporting

lib/linters/important_rule.js
=> Refactor importantRule position reporting

lib/linters/selector_naming.js
=> Refactor selectorNaming position reporting

lib/linters/id_selector.js
=> Refactor idSelector position reporting

lib/linters/color_variables.js, test/specs/linters/color_variables.js
=> Refactor colorVariables position reporting

lib/linters/space_after_property_name.js
=> Refactor spaceAfterPropertyName position reporting

lib/linters/decimal_zero.js
=> Refactor decimalZero position reporting

lib/linters/zero_unit.js
=> Refactor zeroUnit position reporting

lib/linters/qualifying_element.js
=> Refactor qualifyingElement position reporting

lib/linters/property_units.js
=> Refactor propertyUnits position reporting

lib/linters/space_before_brace.js, test/specs/linters/space_before_brace.js
=> Allowed spaces/tabs before newline for space_before_brace

lib/linters/final_newline.js
=> Allowed for \r in final_newline afters

lib/config/defaults.json, lib/linter.js, lib/linters/README.md, lib/linters/space_around_bang.js, package.json, test/specs/linters/space_around_bang.js
#267 
Not really, tests currently will fail due to two bugs I found in `postcss-less` which I've got a [fix pending for](https://github.com/shellscape/postcss-less/pull/95).
=> Linter space around bang

lib/config/defaults.json, lib/linters/README.md, lib/linters/variable_value.js, test/specs/linters/variable_value.js
https://github.com/lesshint/lesshint/issues/355
No
=> variableValue Linter - Allowed Values

gulpfile.js, lib/config/defaults.json, lib/linters/README.md, lib/linters/pseudo_elements.js, test/specs/linters/pseudo_elements.js
#480 
* I added a watch task to simplify development, it run a test task on every js file modification. 
* I only wanted to try to add a new rule, I never used postcss parser before, so my code may not be so optimal
* Pseudo elements list is from MDN
=> New rule "pseudo-elements"
